### ISSUE TITLE
1.12.0버전으로 업그레이드시 Caught SIGILL in blst_cgo_init, consult

### ISSUE THREAD

**Issue by blockchen-admin** [klaytn/klaytn#2076]
쿠버네티스으로 v1.11.1 -> v1.12.0 버전 업그레이드후 

`Caught SIGILL in blst_cgo_init, consult <blst>/bindings/go/README.md.`
위 오류가 발생 합니다. 

실행 방식은 아래와 같습니다.
```
          image: 'klaytn/klaytn:v1.12.0'
          command:
            - ken
          args:
            - '--baobab'
            - '--rpc'
            - '--verbosity'
            - '3'
            - '--rpcaddr'
            - 127.0.0.1
            - '--rpcapi'
            - 'admin,db,klay,debug,miner,net,shh,txpool,personal,web3'
            - '--rpcaddr'
            - 0.0.0.0
            - '--ws'
            - '--wsaddr'
            - 0.0.0.0
            - '--wsport'
            - '3334'
            - '--wsapi'
            - klay
            - '--wsorigins'
            - '*'
            - '--api.filter.getLogs.maxitems'
            - '100000'
```
